name: cinephile
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  better_player: ^0.0.81
  flutter_lints: ^1.0.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  dio: ^4.0.0
  flutter_svg: ^1.0.3
  ionicons: ^0.1.2
  expandable: ^5.0.1
  simple_animations: ^4.0.1
  logger: ^1.1.0
  carousel_slider: ^4.0.0
  native_device_orientation: ^1.0.0
  # google_fonts: ^2.3.0
  helpers: ^1.1.4
  video_viewer: ^1.2.7




dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/cast/
    - assets/images/
    - assets/movies/
