name: fasta
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  dartz: ^0.10.1
  freezed_annotation: ^1.0.0
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_svg: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6
  build_runner: ^2.1.5
  freezed: ^1.0.2


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/
    - assets/4.0x/

# run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/4.0x/splash_black.png
  android: true
  ios: true
  fullscreen: true


