name: utils
description: The interface for helper classes used to make api calls.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  dio_smart_retry: ^1.2.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mocktail: ^0.2.0
  bloc_test: ^9.0.1
